#pragma once

enum TestMode {
  MODE_NONE,
  MODE_SITTING_TEST,
  MODE_ROTATE_TEST,
  MODE_ROTATE_LOOP_TEST,
  MODE_BODY_MOTION_TEST,
  MODE_TRIPOD_GAIT
};

enum LoopDirection { LOOP_STOPPED, LOOP_LEFT, LOOP_RIGHT };
